// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BxBxlBehance: typeof import('~icons/bx/bxl-behance')['default']
    BxBxLinkExternal: typeof import('~icons/bx/bx-link-external')['default']
    BxBxlSpotify: typeof import('~icons/bx/bxl-spotify')['default']
    BxBxlTwitter: typeof import('~icons/bx/bxl-twitter')['default']
    BxBxMailSend: typeof import('~icons/bx/bx-mail-send')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonLogoInstagram: typeof import('~icons/carbon/logo-instagram')['default']
    CarbonLogoLinkedin: typeof import('~icons/carbon/logo-linkedin')['default']
    Contact: typeof import('E:/Code/arhaanb.com-main/src/components/contact.vue')['default']
    Footer: typeof import('E:/Code/arhaanb.com-main/src/components/footer.vue')['default']
    Notionloader: typeof import('E:/Code/arhaanb.com-main/src/components/notionloader.vue')['default']
    Page: typeof import('E:/Code/arhaanb.com-main/src/components/page.vue')['default']
    Project: typeof import('E:/Code/arhaanb.com-main/src/components/project.vue')['default']
    Small: typeof import('E:/Code/arhaanb.com-main/src/components/small.vue')['default']
    Spotify: typeof import('E:/Code/arhaanb.com-main/src/components/spotify.vue')['default']
    Top: typeof import('E:/Code/arhaanb.com-main/src/components/top.vue')['default']
    Website: typeof import('E:/Code/arhaanb.com-main/src/components/website.vue')['default']
  }
}

export { }
